"""JWT auth, password hashing, and role guards."""

import logging
import os
import secrets
from datetime import datetime, timedelta, timezone

import bcrypt
import jwt
from dotenv import load_dotenv
from fastapi import Depends, HTTPException, WebSocket, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

import db
import config

load_dotenv()
log = logging.getLogger("auth")
MIN_PASSWORD_LENGTH = 8

# JWT secret handling: in production, require an explicit secret; in
# development/testing, fall back to a generated secret but warn.
_jwt_env = os.environ.get("JWT_SECRET")
if _jwt_env:
    JWT_SECRET = _jwt_env
else:
    if getattr(config, "PRODUCTION", False):
        log.error("JWT_SECRET not set while running in production; refusing to start with an autogenerated secret")
        raise RuntimeError("Missing JWT_SECRET in production environment")
    # Non-production fallback
    JWT_SECRET = secrets.token_urlsafe(48)
    log.warning("No JWT_SECRET set; using a generated secret for development/testing only")

JWT_ALGO = "HS256"
TOKEN_HOURS = int(os.environ.get("TOKEN_HOURS", "12"))

bearer = HTTPBearer(auto_error=False)


def hash_password(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


def verify_password(plain: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), hashed.encode())
    except (ValueError, TypeError):
        return False


def make_token(user_row) -> str:
    now = datetime.now(timezone.utc)
    payload = {
        "sub": user_row["id"],
        "username": user_row["username"],
        "role": user_row["role"],
        "iat": now,
        "exp": now + timedelta(hours=TOKEN_HOURS),
    }
    return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGO)


def decode_token(token: str):
    """Returns the payload, or None if invalid/expired."""
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGO])
    except jwt.PyJWTError:
        return None


def user_from_token(token: str):
    """Resolve a token to a live, active user row."""
    payload = decode_token(token)
    if not payload:
        return None
    row = db.get_user(payload.get("sub"))
    # Re-check against the DB so deactivation takes effect immediately
    # rather than waiting for the token to expire.
    if not row or not row["is_active"]:
        return None
    return row


async def current_user(
    creds: HTTPAuthorizationCredentials = Depends(bearer),
):
    """Dependency that resolves the current authenticated user.

    Always returns a generic 401 Unauthorized for missing or invalid tokens to
    avoid leaking implementation details about why authentication failed.
    """
    if not creds:
        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized",
            headers={"WWW-Authenticate": "Bearer"},
        )
    row = user_from_token(creds.credentials)
    if not row:
        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized",
            headers={"WWW-Authenticate": "Bearer"},
        )
    # Every authenticated request refreshes presence. Cheap single-row update.
    db.touch_seen(row["id"])
    return row


async def current_admin(user=Depends(current_user)):
    if user["role"] != "admin":
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Admin access required")
    return user


async def user_from_ws(websocket: WebSocket) -> object:
    """Authenticate a WebSocket after the connection opens.

    WebSockets cannot send Authorization headers from the browser, so the
    client sends a short-lived auth frame after the socket opens instead of
    embedding the JWT in the URL.
    """
    try:
        payload = await websocket.receive_json()
    except Exception:
        return None
    token = payload.get("token") if isinstance(payload, dict) else None
    return user_from_token(token) if token else None


def ensure_seed_admin():
    """Create the first admin if no admin exists yet.

    In production this refuses to auto-create an admin with a blank or weak
    password. In non-production modes, a generated password is allowed but
    must not be leaked in logs.
    """
    if db.count_admins() > 0:
        return None
    username = os.environ.get("ADMIN_USERNAME", "admin")
    password = os.environ.get("ADMIN_PASSWORD", "")
    generated = False

    # If running in production, require an explicit, strong ADMIN_PASSWORD.
    if getattr(config, "PRODUCTION", False):
        if not password or len(password) < MIN_PASSWORD_LENGTH:
            log.error("Missing or weak ADMIN_PASSWORD while running in production; refusing to auto-create admin")
            raise RuntimeError("Missing or weak ADMIN_PASSWORD in production environment")
    else:
        # Development/testing: generate a password if none or weak, but mark it
        # generated. Avoid printing the actual password directly to logs.
        if password and len(password) < MIN_PASSWORD_LENGTH:
            log.warning("ADMIN_PASSWORD is too weak; replacing with a generated password for development/testing")
            password = secrets.token_urlsafe(12)
            generated = True
        if not password:
            password = secrets.token_urlsafe(12)
            generated = True

    if db.get_user_by_username(username):
        return None
    db.create_user(
        username=username,
        password_hash=hash_password(password),
        full_name="Super Admin",
        role="admin",
    )
    # Return username and whether password was generated (but do not return the
    # actual password to encourage the caller to avoid logging secrets).
    return (username, True if generated else False)