"""JWT auth, password hashing, and role guards."""

import logging
import os
import secrets
from datetime import datetime, timedelta, timezone

import bcrypt
import jwt
from dotenv import load_dotenv
from fastapi import Depends, HTTPException, WebSocket, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

try:
    from . import db
    from . import config
except ImportError:  # run flat from inside the package dir
    import db
    import config

load_dotenv()
log = logging.getLogger("auth")
MIN_PASSWORD_LENGTH = 8

# JWT secret handling.
#
# Production: an explicit, stable JWT_SECRET is required. It must NOT change on
# restart, otherwise every deploy would log all users out.
#
# Development: optionally rotate the secret on every startup so that restarting
# the dev server forces a fresh login on all pages. Enable by setting
# DEV_ROTATE_JWT_ON_RESTART=true. This flag is ignored in production.
_jwt_env = os.environ.get("JWT_SECRET")
_dev_rotate = os.environ.get("DEV_ROTATE_JWT_ON_RESTART", "false").lower() == "true"
_is_production = getattr(config, "PRODUCTION", False)

if _is_production:
    if not _jwt_env:
        log.error("JWT_SECRET not set while running in production; refusing to start with an autogenerated secret")
        raise RuntimeError("Missing JWT_SECRET in production environment")
    JWT_SECRET = _jwt_env
elif _dev_rotate:
    # Dev: rotate on every startup, invalidating all pre-restart tokens so a
    # server restart sends every open page back to login.
    JWT_SECRET = secrets.token_urlsafe(48)
    log.warning("DEV_ROTATE_JWT_ON_RESTART enabled: rotated JWT secret on startup (all previous sessions invalidated)")
elif _jwt_env:
    JWT_SECRET = _jwt_env
else:
    # Dev with no secret set: generate one (also rotates each restart).
    JWT_SECRET = secrets.token_urlsafe(48)
    log.warning("No JWT_SECRET set; using a generated secret for development/testing only")

JWT_ALGO = "HS256"
TOKEN_HOURS = int(os.environ.get("TOKEN_HOURS", "8"))

# A fresh id is generated every time the process starts. It is stamped into
# every token and re-checked on each request, so restarting the server
# invalidates all previously issued tokens and forces users to log in again -
# even though JWT_SECRET stays fixed across restarts. Set SERVER_BOOT_ID in the
# environment (e.g. to a fixed value, or a deploy hash) if you instead want
# sessions to survive restarts within the same deployment.
SERVER_BOOT_ID = os.environ.get("SERVER_BOOT_ID") or secrets.token_urlsafe(16)

bearer = HTTPBearer(auto_error=False)


def hash_password(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


def verify_password(plain: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), hashed.encode())
    except (ValueError, TypeError):
        return False


def make_token(user_row) -> str:
    now = datetime.now(timezone.utc)
    payload = {
        "sub": user_row["id"],
        "username": user_row["username"],
        "role": user_row["role"],
        "boot": SERVER_BOOT_ID,
        "iat": now,
        "exp": now + timedelta(hours=TOKEN_HOURS),
    }
    return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGO)


def decode_token(token: str):
    """Returns the payload, or None if invalid/expired."""
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGO])
    except jwt.PyJWTError:
        return None


def user_from_token(token: str):
    """Resolve a token to a live, active user row."""
    payload = decode_token(token)
    if not payload:
        return None
    # Tokens issued by a previous server boot are rejected, so a restart forces
    # everyone to log in again (see SERVER_BOOT_ID above).
    if payload.get("boot") != SERVER_BOOT_ID:
        return None
    row = db.get_user(payload.get("sub"))
    # Re-check against the DB so deactivation takes effect immediately
    # rather than waiting for the token to expire.
    if not row or not row["is_active"]:
        return None
    return row


async def current_user(
    creds: HTTPAuthorizationCredentials = Depends(bearer),
):
    """Dependency that resolves the current authenticated user.

    Always returns a generic 401 Unauthorized for missing or invalid tokens to
    avoid leaking implementation details about why authentication failed.
    """
    if not creds:
        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized",
            headers={"WWW-Authenticate": "Bearer"},
        )
    row = user_from_token(creds.credentials)
    if not row:
        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized",
            headers={"WWW-Authenticate": "Bearer"},
        )
    # Every authenticated request refreshes presence. Cheap single-row update.
    db.touch_seen(row["id"])
    return row


async def current_admin(user=Depends(current_user)):
    if user["role"] != "admin":
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Admin access required")
    return user


async def user_from_ws(websocket: WebSocket) -> object:
    """Authenticate a WebSocket after the connection opens.

    WebSockets cannot send Authorization headers from the browser, so the
    client sends a short-lived auth frame after the socket opens instead of
    embedding the JWT in the URL.
    """
    try:
        payload = await websocket.receive_json()
    except Exception:
        return None
    token = payload.get("token") if isinstance(payload, dict) else None
    return user_from_token(token) if token else None


def ensure_seed_admin():
    """Create the first admin if no admin exists yet.

    In production this refuses to auto-create an admin with a blank or weak
    password. In non-production modes, a generated password is allowed but
    must not be leaked in logs.
    """
    if db.count_admins() > 0:
        return None
    username = os.environ.get("ADMIN_USERNAME", "admin")
    password = os.environ.get("ADMIN_PASSWORD", "")
    generated = False

    # If running in production, require an explicit, strong ADMIN_PASSWORD.
    if getattr(config, "PRODUCTION", False):
        if not password or len(password) < MIN_PASSWORD_LENGTH:
            log.error("Missing or weak ADMIN_PASSWORD while running in production; refusing to auto-create admin")
            raise RuntimeError("Missing or weak ADMIN_PASSWORD in production environment")
    else:
        # Development/testing: generate a password if none or weak, but mark it
        # generated. Avoid printing the actual password directly to logs.
        if password and len(password) < MIN_PASSWORD_LENGTH:
            log.warning("ADMIN_PASSWORD is too weak; replacing with a generated password for development/testing")
            password = secrets.token_urlsafe(12)
            generated = True
        if not password:
            password = secrets.token_urlsafe(12)
            generated = True

    if db.get_user_by_username(username):
        return None
    db.create_user(
        username=username,
        password_hash=hash_password(password),
        full_name="Super Admin",
        role="admin",
    )
    # Return username and whether password was generated (but do not return the
    # actual password to encourage the caller to avoid logging secrets).
    return (username, True if generated else False)